name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/ionhome_3_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/cellular_connection_21_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/cellular_connection_8_x2.svg
  - assets/vectors/ionhome_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/vectors/cellular_connection_4_x2.svg
  - assets/images/x_5_mvhxjmy_3_rd_2_uu_9_aea_removebg_preview_1.png
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/rectangle_3_x2.svg
  - assets/vectors/cellular_connection_17_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/images/ellipse_13.png
  - assets/images/ellipse_15.png
  - assets/images/ellipse_16.png
  - assets/images/rectangle_39.png
  - assets/images/ellipse_14.png
  - assets/images/rectangle_38.png
  - assets/images/ellipse_11.png
  - assets/images/ellipse_12.png
  - assets/vectors/ionhome_7_x2.svg
  - assets/vectors/cellular_connection_7_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/battery_11_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/rishield_fill_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/images/ellipse_13.png
  - assets/images/rectangle_38.png
  - assets/images/ellipse_15.png
  - assets/images/ellipse_14.png
  - assets/images/ellipse_11.png
  - assets/images/ellipse_16.png
  - assets/images/ellipse_12.png
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/cellular_connection_5_x2.svg
  - assets/vectors/deviconfacebook_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/deviconlinkedin_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/rishield_fill_1_x2.svg
  - assets/vectors/ionhome_4_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/battery_20_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/images/be_1_ea_5_f_12464_db_77_a_0871_f_3_d_6_dabbe_2_eremovebg_preview_1.png
  - assets/vectors/ellipse_2_x2.svg
  - assets/vectors/battery_21_x2.svg
  - assets/vectors/cellular_connection_10_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/ellipse_31_x2.svg
  - assets/vectors/wifi_23_x2.svg
  - assets/vectors/rectangle_31_x2.svg
  - assets/images/rectangle_52.png
  - assets/images/rectangle_532.png
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/bxcalendar_1_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/bxcalendar_7_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/cellular_connection_15_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/ionhome_1_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/wifi_12_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/cellular_connection_22_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/battery_18_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/vectors/ant_designedit_twotone_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/cellular_connection_18_x2.svg
  - assets/images/rectangle_53.png
  - assets/images/rectangle_531.png
  - assets/images/rectangle_534.png
  - assets/images/rectangle_533.png
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/battery_9_x2.svg
  - assets/vectors/cellular_connection_23_x2.svg
  - assets/vectors/wifi_22_x2.svg
  - assets/images/rectangle_78.png
  - assets/images/rectangle_80.png
  - assets/images/ellipse_28.png
  - assets/images/rectangle_79.png
  - assets/images/rectangle_77.png
  - assets/images/ellipse_29.png
  - assets/images/ellipse_26.png
  - assets/images/ellipse_27.png
  - assets/images/ellipse_23.png
  - assets/vectors/ellipse_291_x2.svg
  - assets/vectors/ellipse_261_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/battery_19_x2.svg
  - assets/vectors/cellular_connection_12_x2.svg
  - assets/vectors/ellipse_281_x2.svg
  - assets/vectors/ellipse_271_x2.svg
  - assets/vectors/ellipse_231_x2.svg
  - assets/vectors/ellipse_24_x2.svg
  - assets/images/programmer_and_engineering_development_coding_web_development_website_design_developer_flat_vector_removebg_preview_11.png
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/rectangle_32_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/ellipse_21_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/ellipse_3_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/ellipse_11_x2.svg
  - assets/images/untitled_design_2_removebg_preview_2.png
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/cellular_connection_9_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/battery_23_x2.svg
  - assets/vectors/cellular_connection_16_x2.svg
  - assets/vectors/arcticonscalendar_10_x2.svg
  - assets/vectors/battery_8_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/logoswhatsapp_icon_x2.svg
  - assets/images/ellipse_4.png
  - assets/images/ellipse_17.png
  - assets/vectors/wifi_15_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/battery_16_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/images/rectangle_55.png
  - assets/images/rectangle_52.png
  - assets/images/rectangle_532.png
  - assets/images/rectangle_54.png
  - assets/images/rectangle_47.png
  - assets/images/rectangle_45.png
  - assets/vectors/battery_22_x2.svg
  - assets/vectors/bxcalendar_9_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/cellular_connection_11_x2.svg
  - assets/vectors/bxcalendar_3_x2.svg
  - assets/vectors/bxcalendar_x2.svg
  - assets/vectors/bxcalendar_10_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/bxcalendar_2_x2.svg
  - assets/vectors/bxcalendar_6_x2.svg
  - assets/images/image_1.png
  - assets/images/untitled_design_2_removebg_preview_2.png
  - assets/vectors/battery_17_x2.svg
  - assets/vectors/group_5_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/wifi_21_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/images/rectangle_532.png
  - assets/images/rectangle_54.png
  - assets/images/rectangle_45.png
  - assets/vectors/bxcalendar_8_x2.svg
  - assets/vectors/bxcalendar_5_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/cellular_connection_14_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/bxcalendar_4_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/battery_13_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/ionhome_2_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/battery_12_x2.svg
  - assets/vectors/cellular_connection_6_x2.svg
  - assets/images/ellipse_17.png
  - assets/images/ellipse_18.png
  - assets/images/ellipse_20.png
  - assets/images/ellipse_4.png
  - assets/images/ellipse_22.png
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/cellular_connection_19_x2.svg
  - assets/vectors/battery_15_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/images/ellipse_4.png
  - assets/vectors/battery_14_x2.svg
  - assets/vectors/ionhome_6_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/cellular_connection_20_x2.svg
  - assets/vectors/frame_24_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/group_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/battery_10_x2.svg
  - assets/vectors/ionhome_5_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/cellular_connection_13_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_73_x2.svg

